config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:create, :destroy]
  resources :posts do
    resources :comments, only: [:create, :destroy]
	end
  resources :sessions, only: [:new, :create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  default_scope -> { order(created_at: :desc) }
  has_many :comments, dependent: :destroy  
  validates :user_id, presence: true
	validates :title, presence: true, length: { minimum: 3, message: 'Too short to post!' }
  validates :body, presence: true, length: { maximum: 4000, message: 'Too long !' }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:destroy, :edit]

  def index
    @posts = current_user.posts.order(created_at: 'desc')
  end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = current_user.posts.build
	end

	def create
	  @post = current_user.posts.build(post_params)
    Rails.logger.info @post.inspect
		if @post.save
      flash[:success] = "Post created!"
    	redirect_to current_user
    else
      render 'new'
    end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
    @post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to current_user
		else
			render "edit"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
    flash[:success] = "Post deleted"
		redirect_to request.referrer || root_url
	end

 private

		def post_params
			params.require(:post).permit(:title, :body, :id, :user_id)
		end

    def correct_user
      @post = current_user.posts.find_by(id:params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<p>
  <%= f.text_field :title, placeholder: 'enter title' %>
  <% if @post and @post.errors.messages[:title].any? %>
  <span class="error"><%= @post.errors.messages[:title][0] %></span>
  <% end %>
</p>
<p>
  <%= f.text_area :body, placeholder: 'enter body text' %>
  <% if @post and @post.errors.messages[:body].any? %>
  <span class="error"><%= @post.errors.messages[:body][0] %></span>
  <% end %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="content">
    <%= link_to post.title, post_path(post) %>
    <% if current_user?(post.user) %>
      <%= link_to 'Edit', edit_post_path(post), class: 'command' %>
      <%= link_to '×', post_path(post),
      	method: :delete, class: 'command', data: { confirm: "sure?" } %>
    <% end %>
  </span> 
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render "form" %> 

app/views/posts/index.html.erb
<h2>
	<%= link_to 'Add New', new_post_path, class: 'header-menu' %>
	My Posts
</h2>
<ul>
<% @posts.each do |post| %>
<li>
<%= link_to post.title, post_path(post) %>
<%= link_to 'Edit', edit_post_path(post), class: 'command' %>
<%= link_to '×', post_path(post),
	method: :delete, class: 'command', data: { confirm: "sure?" } %>
</li>
<% end %>
</ul> 

app/views/posts/new.html.erb
<h2>Add New Post</h2>
<%= render partial: "posts/form" %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= simple_format @post.body %></p>

<h4>Comments</h4>

<% if @post.comments.any? %>
  <ul>
    <% @post.comments.each do |comment| %>
      <% if comment.persisted? %>
        <li>
  	  <%= comment.commenter %>さん:
	  <%= comment.body %>
  	  <%= link_to 'x',
            post_comment_path(@post,comment),
            method: :delete,
            class: 'command',
            data: { confirm: 'Sure?' } %>
        </li>
      <% end %> 
    <% end %>
  </ul>
<% end %>

<%= form_for([@post, @post.comments.build]) do |f| %>
<%= @comment.errors.full_messages.join("\n") if @comment.present? %>
<p>
	<%= f.label :commenter, "commenter" %><br/>
	<%= f.text_field :commenter, placeholder: 'enter your name' %>
</p>

<p>
	<%= f.label :body, "comment" %><br/>
  <%= f.text_field :body, placeholder: 'enter comment' %>
</p>


<p>
  <%= f.submit %>
</p>
<% end %>